const SHA256 = require('crypto-js/sha256');
/**
 * Creating a transaction class that will contain
 * data on the person voting and who they are voting for
 */
class Transaction{
    constructor(fromAddress, toAddress, amount){
        this.fromAddress = fromAddress;
        this.toAddress = toAddress;
        this.amount = amount;
    }
}
/**
 * Creating a Block class where voting information will be encrypted using
the SHA256 algorithm
 */
class Block{
    /**
   * @param {number} timestamp
   * @param {Transaction[]} transactions
   * @param {string} previousHash
   */
    constructor( timestamp, transactions, previousHash = ''){
        this.timestamp = timestamp; //the date the vote was made
        this.transactions = transactions; //data about the vote (who voted, who they voted for)
        this.previousHash = previousHash; //The hash of the previous block in the chain
        this.hash = this.calculateHash(); //the hash of the current block in the chain
        this.nonce = 0; //number that can be changed so new hashes can be mined
    }
    /**
     * Calculates the hash code using the SHA256 algorithm
     */
    calculateHash(){
        return SHA256(this.index + this.previousHash + this.timestamp + JSON.stringify(this.data) + this.nonce).toString();
    }
    /**
     * Makes the hash of the block with a certain amount of zeroes preceding
     * @param {*The # of zeroes you want the hash to start with} difficulty 
     */
    mineBlock(difficulty){
        while(this.hash.substring(0,difficulty) !== Array(difficulty + 1).join("0")) {
            this.nonce++;
            this.hash = this.calculateHash();
        }

        console.log("BLock mined: " + this.hash);
    }
}
/**
 * The class for the blockchain, where the blocks will be stored in an array
 */
class Blockchain{
    constructor(){
        this.chain = [this.createGenesisBlock()]; //The array for blocks to be stored in
        this.difficulty = 2; //The # of zeroes you want preceding the hashes
        this.pendingTransactions = [];
        this.miningReward = 100;
    }
    /**
     * Creates the first block in the block chain
     */
    createGenesisBlock(){
        return new Block( "01/01/2020",[],"0");
    }
    /**
     * Returns the most recently created block in the block chain
     */
    getLatestBlock(){
        return this.chain[this.chain.length-1]
    }
    /**
     * Adds a new block to the blockchain 
     * @param {The block  to be added into the block chain array} newBlock 
     */
    
    /**
     * This will replace the addBlock method
     */
    minePendingTransactions(miningRewardAddress){
        let block = new Block(Date.now(), this.pendingTransactions);
        block.mineBlock(this.difficulty);

        console.log('Block successfully mined!');
        this.chain.push(block);

        this.pendingTransactions = [
            new Transaction(null,miningRewardAddress, this.miningReward)
        ];
    }

    createTransaction(transaction){
        this.pendingTransactions.push(transaction);
    }

    getBalanceOfAddress(address) {
        let balance = 0;
    
        for (const block of this.chain) {
          for (const trans of block.transactions) {
            if (trans.fromAddress === address) {
              balance -= trans.amount;
            }
    
            if (trans.toAddress === address) {
              balance += trans.amount;
            }
          }
        }
    
        return balance;
      }
    /**
     * Checks that each block in the blockchain is valid by ensuring the
     * hashes of the current block match with the hashes generated by the SHA256 algorithm.
     * Then it checks to see if the previous block in the chain's hash matches what the current
     * block in the chain says was the value for the previous block in the chain's hash
     */
    isChainValid(){
        for(let i = 1; i<this.chain.length; i++){ //start at index 1 to compare to the index before it
            const currentBlock = this.chain[i];
            const previousBlock = this.chain[i-1];

            if (currentBlock.hash !== currentBlock.calculateHash()) {
                return false; //hash for the current block is different because it was altered
            }

            if (previousBlock.hash !==currentBlock.previousHash) {
                return false; //hashes of the previous block in the chain did not match
            }
        }
        return true;    //everything matched
    }
}

let votingProcess = new Blockchain(); 
votingProcess.createTransaction(new Transaction('address1', 'address2', 100));
votingProcess.createTransaction(new Transaction('address2', 'address1', 100));

console.log('\n Starting the miner.');
votingProcess.minePendingTransactions('xaviers-address');

console.log('\nBalance of xavier is', votingProcess.getBalanceOfAddress('xaviers-address'));




